# Generated by Django 5.0.8 on 2024-11-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0012_category_search_vector_product_search_vector'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='analytics_history',
            field=models.JSONField(blank=True, help_text='Хранит данные о просмотренных продуктах или категориях.', null=True, verbose_name='История аналитики'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_categories',
            field=models.ManyToManyField(blank=True, related_name='users', to='smartpick.category', verbose_name='Избранные категории'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='users', to='smartpick.product', verbose_name='Избранные товары'),
        ),
    ]
