# Generated by Django 5.0.8 on 2024-08-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedReviewCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=255)),
                ('processed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('category',)},
            },
        ),
    ]
