# Generated by Django 5.0.8 on 2024-08-21 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0003_category_product_aggregatedreview_review_sentence_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
        migrations.AlterUniqueTogether(
            name='processedreviewcache',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='path',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='embedding',
        ),
        migrations.AddField(
            model_name='processedreviewcache',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aggregatedreview',
            name='avg_rating',
            field=models.FloatField(verbose_name='Средний рейтинг'),
        ),
        migrations.AlterField(
            model_name='aggregatedreview',
            name='key_thought',
            field=models.TextField(verbose_name='Ключевая мысль'),
        ),
        migrations.AlterField(
            model_name='aggregatedreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_reviews', to='smartpick.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='aggregatedreview',
            name='rating_category',
            field=models.CharField(max_length=50, verbose_name='Категория рейтинга'),
        ),
        migrations.AlterField(
            model_name='aggregatedreview',
            name='sentence_count',
            field=models.IntegerField(verbose_name='Количество предложений'),
        ),
        migrations.AlterField(
            model_name='aggregatedreviewsentence',
            name='aggregated_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_sentences', to='smartpick.aggregatedreview', verbose_name='Агрегированный отзыв'),
        ),
        migrations.AlterField(
            model_name='aggregatedreviewsentence',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregated_reviews', to='smartpick.sentence', verbose_name='Предложение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='smartpick.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='processedreviewcache',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_reviews', to='smartpick.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='processedreviewcache',
            name='processed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Обработанные данные'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='smartpick.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='review',
            name='corrected_text',
            field=models.TextField(blank=True, null=True, verbose_name='Исправленный текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='smartpick.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_full_text',
            field=models.TextField(verbose_name='Текст отзыва'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review_rating',
            field=models.IntegerField(verbose_name='Рейтинг отзыва'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to='smartpick.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='sentence_text',
            field=models.TextField(verbose_name='Текст предложения'),
        ),
    ]
