# Generated by Django 5.0.8 on 2024-08-22 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0004_delete_productreview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='analysed_at',
            field=models.DateTimeField(blank=True, help_text='Дата и время последнего анализа отзыва', null=True),
        ),
    ]
