# Generated by Django 5.0.8 on 2024-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0006_review_mean_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='mean_distance',
        ),
        migrations.AddField(
            model_name='aggregatedreview',
            name='mean_distance',
            field=models.FloatField(default=99999, verbose_name='Средняя дистанция'),
        ),
    ]
