# Generated by Django 5.0.8 on 2024-08-25 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0008_remove_aggregatedreview_key_thought_keythought'),
    ]

    operations = [
        migrations.AddField(
            model_name='aggregatedreview',
            name='reviews',
            field=models.ManyToManyField(related_name='aggregated_reviews', to='smartpick.review', verbose_name='Отзывы'),
        ),
        migrations.AddField(
            model_name='keythought',
            name='sentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='key_thoughts', to='smartpick.sentence', verbose_name='Предложение'),
        ),
    ]
