# Generated by Django 5.0.8 on 2024-08-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0009_aggregatedreview_reviews_keythought_sentence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='review',
        ),
        migrations.RemoveField(
            model_name='keythought',
            name='sentence',
        ),
        migrations.RemoveField(
            model_name='aggregatedreview',
            name='reviews',
        ),
        migrations.AddField(
            model_name='keythought',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='key_thoughts', to='smartpick.review', verbose_name='Отзыв'),
        ),
        migrations.AlterField(
            model_name='keythought',
            name='aggregated_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_thoughts', to='smartpick.aggregatedreview', verbose_name='Агрегированный отзыв'),
        ),
        migrations.DeleteModel(
            name='AggregatedReviewSentence',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
    ]
