# Generated by Django 5.0.8 on 2024-08-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0010_remove_sentence_review_remove_keythought_sentence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keythought',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_thoughts', to='smartpick.review', verbose_name='Отзыв'),
        ),
    ]
