# Generated by Django 5.0.8 on 2024-09-02 08:13

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpick', '0011_alter_keythought_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
