log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: ':443'

  flower:
    address: ':5555'

certificatesResolvers:
  letsencrypt:
    acme:
      email: hks9@yandex.ru  # Ваш email для уведомлений от Let's Encrypt
      storage: /letsencrypt/acme.json  # Хранение сертификатов
      httpChallenge:
        entryPoint: web

http:
  routers:
    # Django router for smart-pick.ru and asursoft.tech
    web-secure-router:
      rule: 'Host(`smart-pick.ru`) || Host(`www.smart-pick.ru`) || Host(`asursoft.tech`) || Host(`www.asursoft.tech`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt  # Используем Let's Encrypt для сертификатов

    # Flower router for smart-pick.ru and asursoft.tech
    flower-secure-router:
      rule: 'Host(`smart-pick.ru`) || Host(`asursoft.tech`)'
      entryPoints:
        - flower
      service: flower
      tls:
        certResolver: letsencrypt  # Используем Let's Encrypt для сертификатов

    # Media router for smart-pick.ru and asursoft.tech
    web-media-router:
      rule: '(Host(`smart-pick.ru`) || Host(`www.smart-pick.ru`) || Host(`asursoft.tech`) || Host(`www.asursoft.tech`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls:
        certResolver: letsencrypt  # Используем Let's Encrypt для сертификатов

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true
