log:
  level: INFO

entryPoints:
  web:
    address: ':80'
    http:
      redirections:
        entryPoint:
          to: web-secure
          scheme: https

  web-secure:
    address: ':443'

  flower:
    address: ':5555'

tls:
  certificates:
    - certFile: /etc/traefik/certs/fullchain.crt
      keyFile: /etc/traefik/certs/certificate.key

http:
  routers:
    web-secure-router:
      rule: 'Host(`smart-pick.ru`) || Host(`www.smart-pick.ru`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls: {}

    flower-secure-router:
      rule: 'Host(`smart-pick.ru`)'
      entryPoints:
        - flower
      service: flower
      tls: {}

    web-media-router:
      rule: '(Host(`smart-pick.ru`) || Host(`www.smart-pick.ru`)) && PathPrefix(`/media/`)'
      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django-media
      tls: {}

  middlewares:
    csrf:
      headers:
        hostsProxyHeaders: ['X-CSRFToken']

  services:
    django:
      loadBalancer:
        servers:
          - url: http://django:5000

    flower:
      loadBalancer:
        servers:
          - url: http://flower:5555

    django-media:
      loadBalancer:
        servers:
          - url: http://nginx:80

providers:
  file:
    filename: /etc/traefik/traefik.yml
    watch: true